# Generated by Django 4.2.4 on 2023-08-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.IntegerField(verbose_name='Маркет ID')),
                ('market_name', models.CharField(max_length=255, verbose_name='Маркет')),
                ('connect_status', models.IntegerField(choices=[(1, 'Не было первичного подключения от клиента'), (2, 'Не указаны настройки аудио девайса на клиенте'), (3, 'Всё работает'), (4, 'Нет подключения по сети'), (5, 'Не найдено звуковое устройство')], default=1, verbose_name='Статус клиента')),
                ('audio', models.CharField(max_length=255, verbose_name='Аудио устройство')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локальные настройки',
                'verbose_name_plural': 'Локальные настройки',
            },
        ),
    ]
