# Generated by Django 4.2.4 on 2023-09-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenguru', '0002_rename_dateupdate_localsetting_date_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsetting',
            name='audio',
        ),
    ]
